openapi: 3.0.1
info:
  title: Addresses
  description: 'Retrieve, add, or update a borrower's postal mailing address, including the address' primary and active statuses.  Both domestic and international addresses are supported.\n\n**Example Values:**\n```\n{\n\t\"city\": \"Brookfield\",\n\t\"countryCode\": \"USA\",\n\t\"id\": \"1\",\n\t\"isPrimary\": true,\n\t\"isActive\": true,\n\t\"lastUpdateDateTime\": \"2021-11-04T18:33:23Z\",\n\t\"line1\": \"255 Fiserv Dr.\",\n\t\"line2\": \"\",\n\t\"line3\": \"\",\n\t\"locationCode\": \"WORK\",\n\t\"postalCode\": \"53045\",\n\t\"state\": \"WI\"\n}\n```\n\n**BAL Addresses REST API FAQ:**\n1) Where do we get the LocationCode value from?\n\n\t A: The API is expecting one of these \"SCHOOL, HOME, WORK\"\n2) How do I only get the primary address?\n\n\t A: /addresses/api/v1/persons/[personid]/addresses?isPrimary=true\n3) Are addresses validated?\n\n\t A: There is internal validation run, but as long as all required fields are present it will be stored'
  termsOfService: https://FirstData.com/
  contact:
    name: First Data Education
    url: https://FirstData.com/
  license:
    name: First Data Education License
    url: https://FirstData.com/
  version: v1
paths:
  '/api/v1/persons/{personId}/addresses':
    get:
      tags:
        - Addresses
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: isPrimary
          in: query
          schema:
            type: boolean
            nullable: true
        - name: isActive
          in: query
          schema:
            type: boolean
            nullable: true
        - name: X-Correlation-ID
          in: header
          description: Correlation Id for the request
          schema:
            type: string
      responses:
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Address'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      x-proxy-name: Get Address
    post:
      tags:
        - Addresses
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: X-Correlation-ID
          in: header
          description: Correlation Id for the request
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddAddress'
          text/json:
            schema:
              $ref: '#/components/schemas/AddAddress'
          application/*+json:
            schema:
              $ref: '#/components/schemas/AddAddress'
      responses:
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '201':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
      x-proxy-name: Add Address
  '/api/v1/persons/{personId}/addresses/{addressId}':
    get:
      tags:
        - Addresses
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: addressId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: X-Correlation-ID
          in: header
          description: Correlation Id for the request
          schema:
            type: string
      responses:
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      x-proxy-name: Get Address by ID
    put:
      tags:
        - Addresses
      parameters:
        - name: addressId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: personId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: X-Correlation-ID
          in: header
          description: Correlation Id for the request
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAddress'
          text/json:
            schema:
              $ref: '#/components/schemas/UpdateAddress'
          application/*+json:
            schema:
              $ref: '#/components/schemas/UpdateAddress'
      responses:
        '204':
          description: Success
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      x-proxy-name: Update Address
components:
  schemas:
    ProblemDetails:
      type: object
      properties:
        code:
          type: string
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        title:
          type: string
          nullable: true
        traceId:
          type: string
          nullable: true
        type:
          type: string
          nullable: true
      additionalProperties:
        type: object
        additionalProperties: false
    LocationCode:
      enum:
        - SCHOOL
        - HOME
        - WORK
      type: string
    Address:
      type: object
      properties:
        city:
          type: string
          nullable: true
        countryCode:
          type: string
          nullable: true
        id:
          type: string
          nullable: true
        isActive:
          type: boolean
        isPrimary:
          type: boolean
        lastUpdateDateTime:
          type: string
          format: date-time
          nullable: true
        line1:
          type: string
          nullable: true
        line2:
          type: string
          nullable: true
        line3:
          type: string
          nullable: true
        locationCode:
          $ref: '#/components/schemas/LocationCode'
        postalCode:
          type: string
          nullable: true
        state:
          type: string
          nullable: true
      additionalProperties: false
    AddAddress:
      required:
        - city
        - countryCode
        - isPrimary
        - line1
        - postalCode
        - state
      type: object
      properties:
        city:
          type: string
        countryCode:
          type: string
        isPrimary:
          type: boolean
        line1:
          type: string
        line2:
          type: string
          nullable: true
        line3:
          type: string
          nullable: true
        locationCode:
          $ref: '#/components/schemas/LocationCode'
        postalCode:
          type: string
        state:
          type: string
      additionalProperties: false
    UpdateAddress:
      required:
        - city
        - countryCode
        - isPrimary
        - lastUpdateDateTime
        - line1
        - postalCode
        - state
      type: object
      properties:
        city:
          type: string
        countryCode:
          type: string
        isPrimary:
          type: boolean
        lastUpdateDateTime:
          type: string
          format: date-time
        line1:
          type: string
        line2:
          type: string
          nullable: true
        line3:
          type: string
          nullable: true
        locationCode:
          $ref: '#/components/schemas/LocationCode'
        postalCode:
          type: string
        state:
          type: string
      additionalProperties: false
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: http://nwnifieil120.us.ad.usa-ed.net/authorizationdev/connect/token
          scopes: { }
x-error-codes:
  ADD4001:
    Title: City is required.
  ADD4002:
    Title: State is required.
  ADD4003:
    Title: PostalCode is required.
  ADD4005:
    Title: Line3 is required.
  ADD4004:
    Title: Address record not found.
  ADD4009:
    Title: The LastUpdateDateTime is not the latest.
  ADD4010:
    Title: Only the 'isActive' and 'isPrimary' fields may be changed for an address.
  ADD4011:
    Title: Submitted address already exists.
  GBL4000:
    Title: Invalid request.
  GBL4004:
    Title: Person not found.
  GBL5000:
    Title: An unexpected error was encountered.
  GBL5003:
    Title: System not available.
  GBL5004:
    Title: Client ID not authorized to update information on the person.
  GBL4005:
    Title: Loan not found.
  GBL4006:
    Title: Invalid Loan Id.

    
