openapi: 3.0.1
info:
  title: Authorizations
  description: >-
    The Authorization REST API is used to retrieve bearer tokens that the FD
    Education APIs use to authenticate requests. In order to retrieve a token, a
    client will pass in a secret along with their client ID (both supplied by
    Fiserv).
  version: v1
paths:
  '/connect/token':
    post:
      tags:
        - Authorizations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                client_id:
                  type: string
                  required: true
                client_secret:
                  type: string
                  required: true
                grant_type:
                  type: string
                  required: true
                  description: Available Values - client_credentials
                scope:
                  type: string
      responses:
        '200':
          description: 'A bearer token with the expiration, token type, and scope.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  expires_in:
                    type: integer
                    description: >-
                      Contains the number of seconds the token will live after
                      creation
                  token_type:
                    type: string
                  scope:
                    type: string
