openapi: 3.0.1
info:
  title: Documents
  description: "The Documents REST API is used to retrieve outbound correspondence and monthly statements for a specific id associated to a person. Rendering of an individual document in either PDF or Image format is supported.\n* The default is to return 50 documents per page. The limit can be changed up to 100 documents.\n* The default is to return the last 6 months of documents.\n* To get the next set of documents you need to pass one more than the number of documents retrieved."
  version: v1
paths:
  '/api/v1/persons/{personId}/documents':
    get:
      tags:
        - Documents
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: Offset
          in: query
          schema:
            type: integer
            format: int32
            default: '0'
          example: '0'
        - name: Limit
          in: query
          schema:
            type: integer
            format: int32
            default: '50'
          example: '50'
        - name: StartDate
          in: query
          description: Defaults to six months before the current date.
          schema:
            type: string
            format: date-time
        - name: EndDate
          in: query
          description: Defaults to the current date.
          schema:
            type: string
            format: date-time
        - name: type
          in: query
          schema:
            $ref: '#/components/schemas/DocumentType'
        - name: X-Correlation-ID
          in: header
          description: Correlation Id for the request
          schema:
            type: string
      responses:
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page`1'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      x-proxy-name: Get the documents for a person by type Correspondence/Statement
  '/api/v1/persons/{personId}/documents/{id}':
    get:
      tags:
        - Documents
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: id
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: format
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/DocumentFormat'
        - name: X-Correlation-ID
          in: header
          description: Correlation Id for the request
          schema:
            type: string
      responses:
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      x-proxy-name: Get Document as PDF or Image
components:
  schemas:
    DocumentType:
      enum:
        - CORRESPONDENCE
        - STATEMENT
      type: string
    ProblemDetails:
      type: object
      properties:
        code:
          type: string
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        title:
          type: string
          nullable: true
        traceId:
          type: string
          nullable: true
        type:
          type: string
          nullable: true
      additionalProperties:
        type: object
        additionalProperties: false
    DocumentDirection:
      enum:
        - Inbound
        - Outbound
      type: string
    DocumentMetaData:
      type: object
      properties:
        code:
          type: string
          nullable: true
        direction:
          $ref: '#/components/schemas/DocumentDirection'
        id:
          type: string
          nullable: true
        name:
          type: string
          nullable: true
        receivedDate:
          type: string
          format: date-time
          nullable: true
        type:
          $ref: '#/components/schemas/DocumentType'
      additionalProperties: false
    Page`1:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/DocumentMetaData'
          nullable: true
        limit:
          type: integer
          format: int32
        offset:
          type: integer
          format: int32
        totalCount:
          type: integer
          format: int32
      additionalProperties: false
    DocumentFormat:
      enum:
        - PDF
        - IMAGE
      type: string
    Document:
      type: object
      properties:
        base64Content:
          type: string
          nullable: true
        metaData:
          $ref: '#/components/schemas/DocumentMetaData'
      additionalProperties: false
x-error-codes:
  DOC4004:
    Title: Record not found.
  DOC4000:
    Title: Invalid date range.
  GBL4000:
    Title: Invalid request.
  GBL4004:
    Title: Person not found.
  GBL5000:
    Title: An unexpected error was encountered.
  GBL5003:
    Title: System not available.
  GBL5004:
    Title: Client ID not authorized to update information on the person.
  GBL4005:
    Title: Loan not found.
  GBL4006:
    Title: Invalid Loan Id.