openapi: 3.0.1
info:
  title: Permission
  description: API used to retrieve and update a users permissions.
  version: v1
paths:
  '/bal/api/v1/persons/{personId}/permissions':
    get:
      tags:
        - Permissions
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: X-Correlation-ID
          in: header
          description: Correlation Id for the request
          schema:
            type: string
      responses:
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Permission'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      x-proxy-name: Get Permissions
  '/bal/api/v1/persons/{personId}/permissions/{type}':
    get:
      tags:
        - Permissions
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: type
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/PermissionType'
        - name: X-Correlation-ID
          in: header
          description: Correlation Id for the request
          schema:
            type: string
      responses:
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Permission'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      x-proxy-name: Get Permission by Type
    put:
      tags:
        - Permissions
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: type
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/PermissionType'
        - name: X-Correlation-ID
          in: header
          description: Correlation Id for the request
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePermission'
          text/json:
            schema:
              $ref: '#/components/schemas/ChangePermission'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ChangePermission'
      responses:
        '204':
          description: Success
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      x-proxy-name: Update Permission
  '/bal/api/v1/persons/{personId}/permissions/{type}/history':
    get:
      tags:
        - Permissions
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: type
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/PermissionType'
        - name: offset
          in: query
          schema:
            type: integer
            format: int32
        - name: limit
          in: query
          schema:
            type: integer
            format: int32
        - name: X-Correlation-ID
          in: header
          description: Correlation Id for the request
          schema:
            type: string
      responses:
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page`1'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      x-proxy-name: Get Permission History by Type
components:
  schemas:
    ProblemDetails:
      type: object
      properties:
        code:
          type: string
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        title:
          type: string
          nullable: true
        traceId:
          type: string
          nullable: true
        type:
          type: string
          nullable: true
      additionalProperties:
        type: object
        additionalProperties: false
    PermissionType:
      enum:
        - Email1098
        - EmailRegulatory
        - EmailNonRegulatory
        - EmailMarketing
        - PhoneMarketing
        - USPSMarketing
        - AffiliateShareMarketing
      type: string
    Permission:
      type: object
      properties:
        isDefault:
          type: boolean
        lastUpdateDateTime:
          type: string
          format: date-time
        type:
          $ref: '#/components/schemas/PermissionType'
        value:
          type: boolean
      additionalProperties: false
    ChangePermission:
      required:
        - value
      type: object
      properties:
        value:
          type: boolean
      additionalProperties: false
    ChangeHistory:
      type: object
      properties:
        hasValueChanged:
          type: boolean
        updateDateTime:
          type: string
          format: date-time
        value:
          type: boolean
      additionalProperties: false
    Page`1:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/ChangeHistory'
          nullable: true
        endDate:
          type: string
          format: date-time
        limit:
          type: integer
          format: int32
        offset:
          type: integer
          format: int32
        startDate:
          type: string
          format: date-time
        totalCount:
          type: integer
          format: int32
      additionalProperties: false
x-error-codes:
  PRM4004:
    Title: Permission record not found.
  PRM5000:
    Title: Permission type is invalid.
  GBL4000:
    Title: Invalid request.
  GBL4004:
    Title: Person not found.
  GBL5000:
    Title: An unexpected error was encountered.
  GBL5003:
    Title: System not available.