openapi: 3.0.1
info:
  title: Persons
  description: "Retrieve high level account information (such as name, date of birth, customer identification number, role, exception status etc.) by the PersonId. A person can be a borrower, cosigner, or endorser.\n\n**Example Values:**\n```\n{\n\t\"customerIdentificationNumber\": \"1234567890\",\n\t\"dateOfBirth\": \"2022-05-26T16:04:53.632Z\",\n\t\"exceptionStatus\": \"Bankruptcy\",\n\t\"firstName\":\"John\",\n\t\"hasPaymentFraud\": true,\n\t\"lastFourOfSSN\":\"1234\",\n\t\"lastName\":\"Doe\",\n\t\"middleInitial\":\"D\",\n\t\"roles\": {\n\t\t\"isBorrower\": true,\n\t\t\"isCosigner\": true,\n\t\t\"isInfoEligible\": true\n\t},\n\t\"suffix\": \"II\"\n}\n```\n**BAL Persons REST API FAQ:**\n1) What is the field hasPaymentFraud used for? \n\n\t A: This is an indicator manually set by the Business when they suspect fraud on the account"
  termsOfService: 'https://FirstData.com/'
  contact:
    name: First Data Education
    url: 'https://FirstData.com/'
  license:
    name: First Data Education License
    url: 'https://FirstData.com/'
  version: v1
paths:
  '/api/v1/persons/{personId}':
    get:
      tags:
        - Persons
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
        - name: X-Correlation-ID
          in: header
          description: Correlation Id for the request
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      x-proxy-name: Get Person
components:
  schemas:
    ExceptionStatus:
      enum:
        - Bankruptcy
        - Disability
        - Death
      type: string
    Person:
      type: object
      properties:
        customerIdentificationNumber:
          type: string
          nullable: true
        dateOfBirth:
          type: string
          format: date-time
          nullable: true
        exceptionStatus:
          $ref: '#/components/schemas/ExceptionStatus'
        firstName:
          type: string
          nullable: true
        hasPaymentFraud:
          type: boolean
        lastFourOfSSN:
          type: string
          nullable: true
        lastName:
          type: string
          nullable: true
        middleInitial:
          type: string
          nullable: true
        roles:
          $ref: '#/components/schemas/Roles'
        suffix:
          type: string
          nullable: true
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        code:
          type: string
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        title:
          type: string
          nullable: true
        traceId:
          type: string
          nullable: true
        type:
          type: string
          nullable: true
      additionalProperties: {}
    Roles:
      type: object
      properties:
        isBorrower:
          type: boolean
        isCosigner:
          type: boolean
        isInfoEligible:
          type: boolean
      additionalProperties: false
x-error-codes:
  GBL4000:
    Title: Invalid request.
  GBL4004:
    Title: Person not found.
  GBL5000:
    Title: An unexpected error was encountered.
  GBL5003:
    Title: System not available.
  GBL5004:
    Title: Client ID not authorized to update information on the person.
  GBL4005:
    Title: Loan not found.
  GBL4006:
    Title: Invalid Loan Id.
