openapi: 3.0.1
info:
  title: preferences
  description: API used to retireve Payment Alloaction Permissions
  termsOfService: https://FirstData.com/
  contact:
    name: First Data Education
    url: https://FirstData.com/
    email: ''
  license:
    name: First Data Education License
    url: https://FirstData.com/
  version: v1
paths:
  '/bal/api/v1/persons/{personId}/preferences':
    get:
      tags:
        - Preferences
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: X-Correlation-ID
          in: header
          description: Correlation Id for the request
          schema:
            type: string
      responses:
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Preferences'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      x-proxy-name: Get Preferences
  '/bal/api/v1/persons/{personId}/preferences/{type}':
    get:
      tags:
        - Preferences
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: type
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/PreferenceType'
        - name: X-Correlation-ID
          in: header
          description: Correlation Id for the request
          schema:
            type: string
      responses:
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Preferences'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      x-proxy-name: Get Preference by Type
    put:
      tags:
        - Preferences
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: type
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/PreferenceType'
        - name: X-Correlation-ID
          in: header
          description: Correlation Id for the request
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePreference'
          text/json:
            schema:
              $ref: '#/components/schemas/ChangePreference'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ChangePreference'
      responses:
        '204':
          description: Success
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      x-proxy-name: Update Preferences
  '/bal/api/v1/persons/{personId}/preferences/{type}/history':
    get:
      tags:
        - Preferences
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: type
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/PreferenceType'
        - name: offset
          in: query
          schema:
            type: integer
            format: int32
        - name: limit
          in: query
          schema:
            type: integer
            format: int32
        - name: X-Correlation-ID
          in: header
          description: Correlation Id for the request
          schema:
            type: string
      responses:
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page`1'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      x-proxy-name: Get Preference History by Type
components:
  schemas:
    ProblemDetails:
      type: object
      properties:
        code:
          type: string
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        title:
          type: string
          nullable: true
        traceId:
          type: string
          nullable: true
        type:
          type: string
          nullable: true
      additionalProperties:
        type: object
        additionalProperties: false
    PreferenceType:
      enum:
        - UnderpaymentAllocation
        - OverpaymentAllocation
        - AdvanceDueDate
      type: string
    Preferences:
      type: object
      properties:
        isDefault:
          type: boolean
        lastUpdateDateTime:
          type: string
          format: date-time
        type:
          $ref: '#/components/schemas/PreferenceType'
        value:
          type: string
          nullable: true
      additionalProperties: false
    ChangePreference:
      required:
        - value
      type: object
      properties:
        value:
          type: string
      additionalProperties: false
    ChangeHistory:
      type: object
      properties:
        hasValueChanged:
          type: boolean
        updateDateTime:
          type: string
          format: date-time
        value:
          type: string
          nullable: true
      additionalProperties: false
    Page`1:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/ChangeHistory'
          nullable: true
        endDate:
          type: string
          format: date-time
        limit:
          type: integer
          format: int32
        offset:
          type: integer
          format: int32
        startDate:
          type: string
          format: date-time
        totalCount:
          type: integer
          format: int32
      additionalProperties: false
x-error-codes:
  PRE5000:
    Title: Preference type is invalid.
  GBL4000:
    Title: Invalid request.
  GBL4004:
    Title: Person not found.
  GBL5000:
    Title: An unexpected error was encountered.
  GBL5003:
    Title: System not available.